# Header
menu:
  主页: /
  存档: /archives
  关于: /about
# SubNav
subnav:
  github: "https://github.com/csuldw"
  weibo: "http://weibo.com/liudiwei210"
  rss: /atom.xml
  # facebook: "/"
  # google: "/"
  # twitter: "/" 
  # linkedin: "/"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
 
favicon: /favicon.png

avatar: /assets/blogImg/face.png
share: true
duoshuo: "csuldw"
tagcloud: true
animate: true
mathjax: true
fancybox: true
open_in_new: false
#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 中南大学在读硕士，关注机器学习，数据挖掘和生物信息